name: flutter_beacon_example
description: Demonstrates how to use the flutter_beacon plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_beacon:
    path: ../
  get: ^3.20.0

flutter:

  uses-material-design: true
