name: Pub Publish

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  build:
    name: Publishing Test (Dry Run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
          channel: 'stable'
      - run: echo "FLUTTER_ROOT=$FLUTTER_HOME" >> $GITHUB_ENV && echo $FLUTTER_ROOT
      - run: bash scripts/credentials.sh
      - run: rm -rf scripts/
      - run: make
      - run: make deps
      - run: pub global activate dartdoc
      - run: make docs
      - run: pub publish -n -v
